### ISSUE TITLE
给个类似功能的项目

### ISSUE THREAD

**Issue by wangxingkang** [alitajs/gesture-password#1]
http://ignitersworld.com/lab/patternLock.html

**Comment by wangxingkang** [comment]
github仓库 https://github.com/s-yadav/patternLock

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/68912282-ab5f7180-0792-11ea-9a05-123407cd7d3f.png)

**Comment by wangxingkang** [comment]
功能类似吧  只是样式不同

**Comment by xiaohuoni** [comment]
写成了一个类，可以封装成，vue和angular，甚至是小程序的组件。
好像web component也可以尝试一下。

**Comment by wangxingkang** [comment]
哈哈 可以提供 多个框架的封装
