### ISSUE TITLE
gesture-password发包存在问题

### ISSUE THREAD

**Issue by chenguzhen87** [alitajs/gesture-password#19]
![image](https://user-images.githubusercontent.com/28331609/69917751-69c60a80-14a4-11ea-812a-0bbb457ab48c.png)

**Comment by xiaohuoni** [comment]
不知道康康有没有改过@wangxingkang

**Comment by wangxingkang** [comment]
我看下

**Comment by wangxingkang** [comment]
@chenguzhen87 请看最新代码

**Comment by chenguzhen87** [comment]
复核代码，我所指发包没有问题，自己本地缓存

**Comment by wangxingkang** [comment]
那我关了
