### ISSUE TITLE
gesture-password-vue打包优化

### ISSUE THREAD

**Issue by chenguzhen87** [alitajs/gesture-password#20]
能否把vue-runtime-helpers/dist/normalize-component.mjs打包进去
![image](https://user-images.githubusercontent.com/28331609/69931770-7299f900-1503-11ea-92d0-bb1985988896.png)
![image](https://user-images.githubusercontent.com/28331609/69931804-8e9d9a80-1503-11ea-985a-4fcdb6eed4cf.png)

**Comment by wangxingkang** [comment]
添加编译配置
```
bundleNodeModules: true
```
